title: Emerald-quill
description: A website with a blog
footer_text: Copyright 2021 Mégane Maridor
header_feature_image: ../uploads/capture-d’écran-1-.png
header_text: My Dream Blog
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
